python ./main.py \
  --base_model_name meta-llama/Llama-2-7b-hf \
  --tasks "yelp_review_full,amazon,mnli,cb,copa,qqp,rte,imdb,sst2,dbpedia_14,ag_news,yahoo_answers_topics,multirc,boolq,wic" \
  --prefix_len 10 \
  --max_length 256 \
  --lr 0.03 \
  --batch_size 16 \
  --k_per_class 1000 \
  --num_epochs 2 \
  --seed 42 \
  --save_path "./" \
  --eval_all_tasks \
  --eval_seen_only \
  --fix_test_data \
  --test_fixed_dir "./" \
  --data_root "./"